package com.hnu.backend.rag.model;

/** 路由决策的稳定原因码，用于测试、评测和不含正文的结构化日志。 */
public enum RoutingReasonCode {
  KNOWLEDGE_SOURCE_REQUIRED,
  EXTERNAL_SOURCE_REQUIRED,
  GENERAL_CHAT,
  AMBIGUOUS,
  LOW_CONFIDENCE_FALLBACK,
  CLASSIFIER_DEGRADED,
  MCP_DISABLED_FALLBACK,
  TOOL_NOT_ALLOWED_FALLBACK,
  TOOL_NOT_READ_ONLY_FALLBACK,
  INVALID_TOOL_ARGUMENTS_FALLBACK
}
